url: https://xyztobixyz.github.io/
baseurl: https://xyztobixyz.github.io/

# Site settings
title: Toebyyy
email: xyztobixyz@gmail.com
description: "Toebyys Website"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Tobias Schmitz
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/xyztobixyz
  - title: facebook
    url: https://facebook.com/tobiasschmitz94
  - title: bitbucket 
    url: http://bitbucket.org/TTTheKing
  - title: github
    url: http://github.com/xyztobixyz

# Postal address (add as many lines as necessary)
address:
  - line: Toebyyys Home
  - line: In Town Near BY

# Build settings
markdown: kramdown
permalink: pretty